### ISSUE TITLE
Options not displaying on select

### ISSUE THREAD

**Issue by rolljee** [spastai/forms-frame#6]
I've tried to make a basic form with all the element you gave on the package.

I've noticied that none of the select are displaying any option... any idea ? 

```
`testFomulaire() {
      fieldTypes = [
        { title: "String", value: "text" },
        { title: "Checkbox", value: "checkbox" },
        { title: "Hidden", value: "hidden" }
      ]

      fieldForm = [
        { field: "field", type: 'text', label: "Field" },
        { field: "label", type: 'text', label: "Label" },
        { field: "type", type: 'select', label: "Type", options: fieldTypes, clazz: "form-control" },
      ]

      var categories = [
        { title: "Audio", value: "audio" },
        { title: "Video", value: "video" }
      ];
      var demoForm = [
        { field: 'url', type: 'text', label: "Feed URL", placeholder: "Enter URL", clazz: "form-control" },
        { field: 'media', type: 'select', label: "Media", placeholder: "Select category", clazz: "form-control", options: categories },
        { field: "form", type: "subformRows", form: fieldForm },
        { field: 'check', type: 'checkbox', label: "Agreement", placeholder: "Enter URL", clazz: "form-control" },
        { field: 'uml', type: 'textarea', label: "Uml", placeholder: "Write PlantUML", clazz: "form-control" },
      ];
      console.log(demoForm);
```

```
  return demoForm;`
```

We are using Meteor 1.3 with basic Blaze Meteor syntax. Any help would be  much appreciated.

**Comment by rolljee** [comment]
`_.each(this.options,function(option){
      console.log("Options",option);   
      var object = {};
      object.value = option.value;
      object.title = option.title;                  
            result.push(object);
    });`
i've modified your file forms-frame/packages/forms/fieldSelect.js to make a workaround for me, feel free to test it or can you tell me what i am doing wrong with your package if it's working on you :)

**Comment by spastai** [comment]
`{ field: 'media', type: 'select', label: "Media", placeholder: "Select category", clazz: "form-control", options: categories },` field options expect to get a function like in https://github.com/spastai/forms-frame/blob/master/client/FormsFrame.coffee#L3 
The intention here is that usually those options are loaded from somewhere - so it is a method rather than a simple array.

**Comment by rolljee** [comment]
I understand now, i never wrote in coffee, kinda hard to understand the full logic behind. Got it now ! Thx
